name: test

on:
  # Every push onto the main branch and releases triggers a retest.
  push:
    branches:
      - master
      - v12-branch
  # All pull_requests trigger a retest.
  pull_request:
  workflow_dispatch:

jobs:

  lin:
    strategy:
      fail-fast: false
      matrix:
        os: [
          '20.04'
        ]
    runs-on: ubuntu-${{ matrix.os }}
    name: '🐧 Ubuntu ${{ matrix.os }}'
    steps:

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update -qq
        sudo apt install -y make g++ git bison flex gperf libreadline-dev autoconf python3-sphinx

    - name: Build, check and install
      run: |
        autoconf
        ./configure --prefix=$PWD/inst
        make check
        make install
        tar zcf iverilog.tar.gz inst

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }} build
        path: iverilog.tar.gz
