name: test

on:
  # Every push onto the main branch and releases triggers a retest.
  push:
    branches:
      - master
      - v12-branch
  pull_request:
    branches:
      - master
      - v12-branch
  workflow_dispatch:

jobs:
  lin:
    runs-on: ubuntu-latest
    container: rockylinux:8.9.20231119
    name: 'Rocky8'
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        dnf install 'dnf-command(config-manager)' -y
        dnf config-manager --enable powertools -y
        dnf install -y autoconf flex bison gperf git
        dnf install -y gcc-c++
        dnf install -y make

    - name: Build, check and install
      run: |
        autoconf
        ./configure --prefix=$PWD/inst
        make check -j
        make install
        tar czf iverilog.tar.gz inst

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Rocky8-iverilog
        path: iverilog.tar.gz

  mac:
    runs-on: macos-latest
    name: 'macOS'
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew install autoconf flex bison git make
        pip3 install --break-system-packages docopt

    - name: Build, check and install
      run: |
        export PATH="/opt/homebrew/opt/bison/bin:/opt/homebrew/opt/flex/bin:$PATH"
        export CPPFLAGS="-DHAVE_SYS_RESOURCE_H"
        autoconf
        ./configure --prefix=$PWD/inst
        gmake check -j
        gmake install
        tar czf iverilog.tar.gz inst

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS-iverilog
        path: iverilog.tar.gz
