name: test

on:
  # Every push onto the main branch and releases triggers a retest.
  push:
    branches:
      - master
      - v12-branch
  # All pull_requests trigger a retest.
  pull_request:
  workflow_dispatch:

jobs:
  lin:
    runs-on: ubuntu-latest
    container: rockylinux:8.9.20231119
    name: 'Rocky8'
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        dnf install 'dnf-command(config-manager)' -y
        dnf config-manager --enable powertools -y
        dnf install -y autoconf flex bison gperf git
        dnf install -y gcc-c++
        dnf install -y make

    - name: Build, check and install
      run: |
        autoconf
        ./configure --prefix=$PWD/inst
        make check -j
        make install
        tar zcf iverilog.tar.gz inst

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Rocky8-iverilog
        path: iverilog.tar.gz
